version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI and AWS SAM CLI to the latest version
      - pip install --upgrade --user awscli
      - pip install --upgrade aws-sam-cli

  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean -q
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn compile dependency:copy-dependencies -DincludeScope=runtime -q
      - docker build -t clamav:latest .
      - docker tag clamav:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/clamav:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/clamav:latest
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
